// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF3-7lfPZ-SSu195aR20ZhMowNBRrKXJA',
    appId: '1:229486356731:web:130ad9ea580521d80ca85e',
    messagingSenderId: '229486356731',
    projectId: 'projectstoredatatest-980d6',
    authDomain: 'projectstoredatatest-980d6.firebaseapp.com',
    storageBucket: 'projectstoredatatest-980d6.firebasestorage.app',
    measurementId: 'G-BV5MKCCD78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT6PxqSVKJNctB4OBuM8BdrXdAiYNAD-M',
    appId: '1:229486356731:android:c8b8ee4bab14c6420ca85e',
    messagingSenderId: '229486356731',
    projectId: 'projectstoredatatest-980d6',
    storageBucket: 'projectstoredatatest-980d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-sXXFNIcCEwULLMeUDGRrGUbuvOjFJxw',
    appId: '1:229486356731:ios:b266e43ed2535f030ca85e',
    messagingSenderId: '229486356731',
    projectId: 'projectstoredatatest-980d6',
    storageBucket: 'projectstoredatatest-980d6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
